spring.application.name=my-dashboard

# 1. PostgreSQL DB ?? ??
# ??? ?????? ?? ??? ?? ??? 5432???.
spring.datasource.url=jdbc:postgresql://localhost:5432/macrodb
spring.datasource.username=postgres
spring.datasource.password=5432
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. JPA / Hibernate ?? ??
# update: ?? ??? ???? DB? ???? ??? ?? ??(CREATE), ??? ??? ALTER? ???? ????.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. ?? ??? ??
# ???? ????? ?? SQL ??? ???? ???? ??? ????? ?????.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#4. encoding
service.servlet.encoding.force=true

#FRED API CONFIGURATION
fred.api.key=a2bf295de1e76f415eee7c3a3ff64a68
fred.api.base-url=https://api.stlouisfed.org/fred

